# Generated by Django 4.2.1 on 2023-06-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Todo',
        ),
    ]
